FROM mcr.microsoft.com/devcontainers/java:17

# Instal Node.js dan npm untuk pengembangan frontend
RUN apt-get update && apt-get install -y \
    nodejs \
    npm

# Tambahkan tools lain jika diperlukan (misalnya Git)
RUN apt-get install -y git
